version: '3'

services:
  app:
    image: docker.io/makos/http-print-server
    build:
      context: .
    environment:
      - PRINTERS=
      - PORT=8080
      - API_KEY=
    ports:
      - 8080:8080
    